### ISSUE TITLE
Recommend adding #!/bin/bash line

### ISSUE THREAD

**Issue by BenLiyanage** [foxundermoon/vs-shell-format#58]
Would it be possible to recommend adding the `#!` line in bash files?

**Comment by beltaurus** [comment]
Why would we recommend this, if it is not necessary, or even not desired:
People are developing scripts that are meant to change the current environment. Which means that those scripts have to be sourced.
A shebang at the start of such script might give the impression that the script is meant to be executed. A well-designed script will not have execution privileges, but still, the shebang is not desired at all for this scenario...

The 'shellcheck' application does it right:
![image](https://user-images.githubusercontent.com/54114043/90164818-b7418980-dd4c-11ea-853c-a9e0b2a4c4fd.png)

For a script that needs to be sourced, you simply add:
```bash
# shellcheck shell=bash
```

If the script was meant to be executed, then you can indeed add the shebang...

Since `shfmt` is a formatting tool, and not a general coding style tool, I would leave it to `shellcheck` to manage this rule...
